import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  favoritePokemons: {},
  status: null,
};

export const favoritePokemon = createSlice({
  name: "favoritePokemon",
  initialState,

  reducers: {
    addFavorite: (state, action) => {
      const { id } = action.payload;
      console.log("add", id);
      state.favoritePokemons = {
        ...state.favoritePokemons,
        [id]: action.payload,
      };
      console.log(state.favoritePokemons);
    },

    removeFavorite: (state, action) => {
      const { id } = action.payload;
      console.log("remove", id);
      state.favoritePokemons = { ...state.favoritePokemons };
      delete state.favoritePokemons[id];
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {},
});

export const { addFavorite, removeFavorite } = favoritePokemon.actions;

export default favoritePokemon.reducer;
