import { createSlice } from '@reduxjs/toolkit';
import { getPokemons } from './pokemonListAPI';

const initialState = {
  pokemonList: [],
  status: null,
};

export const pokemonList = createSlice({
  name: 'pokemonList',
  initialState,

  reducers: {
   
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getPokemons.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(getPokemons.fulfilled, (state, action) => {
        state.pokemonList = action.payload;
      });
  },
});



export default pokemonList.reducer;
